/* Conformance: the browser engine must reproduce the Python engine exactly.
 *
 * Replays the double-disruption scenario through web/engine.js and requires the
 * resulting run to equal submission/TechTitan_evidence_agentic.json, which was
 * generated by run_demo.py from engine.py. Run identifiers and wall-clock
 * timestamps are excluded; every decision, allocation, ledger entry, receipt
 * digest and verification result must match.
 *
 * Usage: node tools/conformance.mjs
 */
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { createRequire } from 'module';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const require = createRequire(import.meta.url);
const RouteGuard = require(join(root, 'web', 'engine.js'));

const IGNORED = new Set(['timestamp']);

function diff(actual, expected, path, out) {
  if (out.length >= 12) return out;
  const ta = actual === null ? 'null' : Array.isArray(actual) ? 'array' : typeof actual;
  const te = expected === null ? 'null' : Array.isArray(expected) ? 'array' : typeof expected;
  if (ta !== te) {
    out.push(`${path}: type ${ta} != ${te}`);
    return out;
  }
  if (te === 'array') {
    if (actual.length !== expected.length) {
      out.push(`${path}: length ${actual.length} != ${expected.length}`);
      return out;
    }
    for (let i = 0; i < expected.length; i++) diff(actual[i], expected[i], `${path}[${i}]`, out);
    return out;
  }
  if (te === 'object') {
    const ka = Object.keys(actual).filter((k) => !IGNORED.has(k)).sort();
    const ke = Object.keys(expected).filter((k) => !IGNORED.has(k)).sort();
    const missing = ke.filter((k) => !ka.includes(k));
    const extra = ka.filter((k) => !ke.includes(k));
    if (missing.length) out.push(`${path}: missing key(s) ${missing.join(', ')}`);
    if (extra.length) out.push(`${path}: unexpected key(s) ${extra.join(', ')}`);
    for (const k of ke) if (ka.includes(k)) diff(actual[k], expected[k], `${path}.${k}`, out);
    return out;
  }
  if (actual !== expected) out.push(`${path}: ${JSON.stringify(actual)} != ${JSON.stringify(expected)}`);
  return out;
}

const read = (...p) => JSON.parse(readFileSync(join(root, ...p), 'utf8'));
const evidence = read('submission', 'TechTitan_evidence_agentic.json');
const evaluation = read('submission', 'TechTitan_evaluation_agentic.json');
const problems = [];

// 1. The full demo trace, event by event, including receipt digests.
const store = new RouteGuard.MemoryStore();
const actual = new RouteGuard.Agent(store).run(store.create('double_disruption').id);
diff(actual.world, evidence.world, 'world', problems);
diff(actual.events, evidence.events, 'events', problems);
const summary = actual.world.verification.totals;
console.log(`demo trace   : ${actual.events.length} events, status ${actual.world.status}, ` +
  `${summary.units} units, INR ${summary.cost}, ${summary.carbon} kg CO2e, ETA ${summary.eta}h ` +
  `(python: ${evidence.events.length} events, ${evidence.world.status})`);

// 2. Every scenario's outcome, as recorded by evaluate.py.
for (const expected of evaluation.scenarios) {
  const s = new RouteGuard.MemoryStore();
  const r = new RouteGuard.Agent(s).run(s.create(expected.scenario).id);
  diff({
    scenario: expected.scenario, status: r.world.status, steps: r.world.steps,
    replans: r.world.replan_count, verification: r.world.verification
  }, expected, `scenario(${expected.scenario})`, problems);
}
console.log(`scenarios    : ${evaluation.scenarios.length} replayed ` +
  `(${evaluation.scenarios.map((s) => `${s.scenario}=${s.status}`).join(', ')})`);

// 3. The optimizer and the disclosed baseline, over all benchmark cases.
let optimizerChecked = 0;
for (const row of evaluation.cases) {
  const result = RouteGuard.optimize(row.offers, row.goal);
  const totals = result.best ? result.best.totals : null;
  diff(totals, row.planner_totals, `case(${row.case}).planner_totals`, problems);
  diff(result.examined, row.examined, `case(${row.case}).examined`, problems);
  diff(result.best !== null, row.planner_feasible, `case(${row.case}).planner_feasible`, problems);
  const baseline = RouteGuard.Agent.baseline(row.offers, row.goal, row.goal.units);
  diff(baseline.feasible, row.baseline_feasible, `case(${row.case}).baseline_feasible`, problems);
  optimizerChecked += 1;
}
const feasible = evaluation.cases.filter((r) => r.planner_feasible).length;
console.log(`benchmark    : ${optimizerChecked} cases, identical allocations, search counts and ` +
  `baseline verdicts (${feasible} feasible, ${optimizerChecked - feasible} infeasible)`);

if (problems.length) {
  console.error('\nCONFORMANCE FAILED - browser engine diverges from engine.py:');
  for (const p of problems) console.error('  ' + p);
  process.exit(1);
}
console.log('\nCONFORMANCE PASSED - browser engine matches engine.py exactly.');
